### ISSUE TITLE
如何引用你的jniLibs

### ISSUE THREAD

**Issue by NewHuLe** [xiaomo/AndroidPlayerLibrary#1]
demo运行了下还可以，但是我无法迁移那些.so文件到自己的项目，是不是生成.so文件的时候，什么c文件用的是你自己的包名，我们的项目是不能直接复制.so文件，对吗？一直报下面这个错
  Process: com.ces.myapplication, PID: 5417
    java.lang.UnsatisfiedLinkError: Native method not found: vedio.libvlc.LibVLC.nativeInit:()V
            at vedio.libvlc.LibVLC.nativeInit(Native Method)
            at vedio.libvlc.LibVLC.init(LibVLC.java:408)

同事拷贝java和so才可以用，org/videolan/libvlc/不能放到其他包里面，要放在根目录

**Comment by hkusoft** [comment]
If you are using Android studio, and wish to include all *.so into the APK, you can refer to [this link](https://xinyustudio.wordpress.com/2015/12/03/how-to-package-native-library-so-in-android-studio/) to solve it.
