### ISSUE TITLE
请问你用的vlc的版本是多少?

### ISSUE THREAD

**Issue by cro4k** [xiaomo/AndroidPlayerLibrary#4]
你这个只支持arm的cpu啊，我想试试找一下x86的so库，但又不知道版本号，vlc更新又太快，而且很多版本都不兼容

**Comment by xiaomo** [comment]
呵呵

**Comment by qvoid** [comment]
看[这里](https://wiki.videolan.org/AndroidCompile/)，可以自己搭建一个编译环境，编译出自己要的so库。

**Comment by cro4k** [comment]
感谢楼上的建议，之前的想法是想找一些现成的编译好的项目，刚接触这一块，理解不是很深入。对于官方的源码理解也不是很多，看到这个项目后感觉很棒，想学习一下代码的实现，也很感谢项目主人提供的源码，但是vlc的版本变动很大，很多接口都变了，所以才想知道vlc的版本。（PS：一句呵呵真的让小白感受到了来自大神的蔑视啊 -_-||）如有打扰，请见谅

**Comment by xiaomo** [comment]
我的qq：2402921232
