### ISSUE TITLE
解析RTSP流 死了

### ISSUE THREAD

**Issue by KollerWithDoris** [xiaomo/AndroidPlayerLibrary#9]
11-18 15:35:19.459: W/VLC(25593): core video output: picture is too late to be displayed (missing 11228 ms)

VLC报  picture is too late to be displayed (missing 11228 ms)  这是什么问题。
求告知

**Comment by qvoid** [comment]
你这个日志表明解析没有问题，视频有开始播放，只是播放过程中音视频出现了严重不同步，先看看视频源是不是有问题，也有可能是跟网络带宽有关。
